/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal.IntefaceFuncionario;

import Principal.IntefaceProjeto.MenuConsultaProjeto;
import javax.swing.JOptionPane;


public class MenuCadFuncionarioProj extends javax.swing.JFrame {

    private static MenuCadFuncionarioProj menuCadFuncionarioProj = null;
    
    private MenuCadFuncionarioProj() {
        initComponents();
    }
    
    public static MenuCadFuncionarioProj getMenuCadFuncionarioProj(){
        if(menuCadFuncionarioProj == null ){
            menuCadFuncionarioProj = new MenuCadFuncionarioProj();
        }
    
        return menuCadFuncionarioProj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lbConsulta = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbNomeProj = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        lbNomeCliente = new javax.swing.JLabel();
        cxCpfCliente = new javax.swing.JLabel();
        cxNomeCliente = new javax.swing.JLabel();
        cxCodIdentificador = new javax.swing.JTextField();
        btListar = new javax.swing.JButton();
        btAddFunc = new javax.swing.JButton();
        btRemoverFunc = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSairMenuConsultaCliente = new javax.swing.JButton();
        opcFunc = new javax.swing.JComboBox<>();
        cxNomeProj = new javax.swing.JLabel();
        cxCod = new javax.swing.JLabel();
        lbCod1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Cadastro Funcionário");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        lbConsulta.setFont(new java.awt.Font("Nimbus Mono PS", 1, 24)); // NOI18N
        lbConsulta.setForeground(new java.awt.Color(255, 255, 255));
        lbConsulta.setText("Consulta Funcionário");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(lbConsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lbConsulta)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        lbNomeProj.setForeground(new java.awt.Color(255, 255, 255));
        lbNomeProj.setText("Nome Projeto:");

        lbCpf.setForeground(new java.awt.Color(255, 255, 255));
        lbCpf.setText("CPF");

        lbNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        lbNomeCliente.setText("Cliente:");

        cxCpfCliente.setForeground(new java.awt.Color(255, 255, 255));
        cxCpfCliente.setText("...");

        cxNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        cxNomeCliente.setText("...");

        cxCodIdentificador.setForeground(new java.awt.Color(51, 51, 51));
        cxCodIdentificador.setText("Digite o ID");
        cxCodIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCodIdentificadorActionPerformed(evt);
            }
        });

        btListar.setBackground(new java.awt.Color(102, 102, 102));
        btListar.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        btListar.setForeground(new java.awt.Color(255, 255, 255));
        btListar.setText("Listar Funcionários");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        btAddFunc.setBackground(new java.awt.Color(102, 102, 102));
        btAddFunc.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        btAddFunc.setForeground(new java.awt.Color(255, 255, 255));
        btAddFunc.setText("Adicionar");
        btAddFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddFuncActionPerformed(evt);
            }
        });

        btRemoverFunc.setBackground(new java.awt.Color(102, 102, 102));
        btRemoverFunc.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        btRemoverFunc.setForeground(new java.awt.Color(255, 255, 255));
        btRemoverFunc.setText("Remover");
        btRemoverFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverFuncActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(102, 102, 102));
        btLimpar.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSairMenuConsultaCliente.setBackground(new java.awt.Color(102, 102, 102));
        btSairMenuConsultaCliente.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        btSairMenuConsultaCliente.setForeground(new java.awt.Color(255, 255, 255));
        btSairMenuConsultaCliente.setText("Sair");
        btSairMenuConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairMenuConsultaClienteActionPerformed(evt);
            }
        });

        opcFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engenheiro", "Arquiteto", "Funcionário Geral" }));
        opcFunc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opcFuncItemStateChanged(evt);
            }
        });

        cxNomeProj.setForeground(new java.awt.Color(255, 255, 255));
        cxNomeProj.setText("...");

        cxCod.setForeground(new java.awt.Color(255, 255, 255));
        cxCod.setText("...");

        lbCod1.setForeground(new java.awt.Color(255, 255, 255));
        lbCod1.setText("Código");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbNomeProj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbNomeCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cxNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cxCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(cxNomeProj, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbCod1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btListar)
                                    .addComponent(cxCod, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(opcFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(btLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btSairMenuConsultaCliente))
                            .addComponent(cxCodIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btAddFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRemoverFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCliente)
                    .addComponent(cxNomeCliente)
                    .addComponent(lbCpf)
                    .addComponent(cxCpfCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeProj)
                    .addComponent(cxNomeProj)
                    .addComponent(lbCod1)
                    .addComponent(cxCod))
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxCodIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListar))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddFunc)
                    .addComponent(btRemoverFunc))
                .addGap(122, 122, 122)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLimpar)
                    .addComponent(btSairMenuConsultaCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        MenuConsultaProjeto.getMenuConsultaProjeto().setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MenuConsultaProjeto.getMenuConsultaProjeto().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void cxCodIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCodIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCodIdentificadorActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        MenuListaFuncionarios.getMenuListaFuncionarios().setVisible(true);
    }//GEN-LAST:event_btListarActionPerformed

    private void btAddFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddFuncActionPerformed
        
    }//GEN-LAST:event_btAddFuncActionPerformed

    private void btRemoverFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverFuncActionPerformed
        
    }//GEN-LAST:event_btRemoverFuncActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        //limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairMenuConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairMenuConsultaClienteActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Confirmação de saída", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            sair();
        }
    }//GEN-LAST:event_btSairMenuConsultaClienteActionPerformed
    public void sair(){
        this.dispose();
    }
    
    
    
    private void opcFuncItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opcFuncItemStateChanged

        switch ((String) opcFunc.getSelectedItem()) {

            case "Engenheiro":
            lbCpf.setText("CREA:");
            break;

            case "Arquiteto":
            lbCpf.setText("Código Registro:");
            break;

            case "Funcionário Geral":
            lbCpf.setText("CPF:");
            break;
        }
    }//GEN-LAST:event_opcFuncItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCadFuncionarioProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCadFuncionarioProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCadFuncionarioProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCadFuncionarioProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCadFuncionarioProj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddFunc;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btRemoverFunc;
    private javax.swing.JButton btSairMenuConsultaCliente;
    private javax.swing.JLabel cxCod;
    private javax.swing.JTextField cxCodIdentificador;
    private javax.swing.JLabel cxCpfCliente;
    private javax.swing.JLabel cxNomeCliente;
    private javax.swing.JLabel cxNomeProj;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbCod1;
    private javax.swing.JLabel lbConsulta;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbNomeCliente;
    private javax.swing.JLabel lbNomeProj;
    private javax.swing.JComboBox<String> opcFunc;
    // End of variables declaration//GEN-END:variables
}
